#!/bin/bash

# Where is this script located?
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$DIR"
export GOPATH="$PWD"/.gopath/
export BASEDIR="$PWD"

case "$1" in
	build)
		go build -o grypt
		;;
	test)
		go test
		;;
	install)
		go install polydawn.net/grypt
		;;
	*)
		echo "Usage: $0 {build|test|install}" 1>&2;
		exit 1
	;;
esac


